---
name: Check Formatting of Code Base

defaults:
    run:
        shell: bash

on:
    push:
    pull_request:

jobs:
    prettier:
        name: Check TypeScript, JavaScript, style, and HTML file formatting with prettier
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Install Dependencies
              run: npm ci --ignore-scripts
            - name: Check formatting with prettier
              run: npm run format:check
